//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCY_ImageText
    {
        public string ID { get; set; }
        public string sClientId { get; set; }
        public string sSourceId { get; set; }
        public int iType { get; set; }
        public string sContext { get; set; }
        public string sImagesUrl { get; set; }
        public string sVideoUrl { get; set; }
        public bool bIsTop { get; set; }
        public string sGoodsNo { get; set; }
        public Nullable<decimal> dCommodityPrices { get; set; }
        public Nullable<decimal> dRetailprices { get; set; }
        public Nullable<decimal> dTradePrices { get; set; }
        public Nullable<decimal> dPackPrices { get; set; }
        public string sRemark { get; set; }
        public System.DateTime dInsertTime { get; set; }
        public Nullable<System.DateTime> dUpdateTime { get; set; }
        public Nullable<System.DateTime> dShareTime { get; set; }
        public bool bIsDeleted { get; set; }
    }
}
