//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCY_VipPackage
    {
        public string ID { get; set; }
        public string sVipName { get; set; }
        public decimal dVipPrices { get; set; }
        public decimal dOldPrices { get; set; }
        public decimal dSavePrices { get; set; }
        public decimal dBonusMoney { get; set; }
        public int sVipDays { get; set; }
        public int iSort { get; set; }
    }
}
