//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCY_Client
    {
        public string ID { get; set; }
        public string sNickName { get; set; }
        public string sPhone { get; set; }
        public string sPassword { get; set; }
        public string sParentUnionid { get; set; }
        public string sUnionid { get; set; }
        public string sOpenId { get; set; }
        public string sHeadImg { get; set; }
        public string sWeiXinNo { get; set; }
        public decimal dBonus { get; set; }
        public bool bIsVip { get; set; }
        public string sVipName { get; set; }
        public System.DateTime dExpireTime { get; set; }
        public string sPhotoName { get; set; }
        public string sIntroduce { get; set; }
        public System.DateTime dInsertTime { get; set; }
        public int iStatus { get; set; }
    }
}
