//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CCY_Client> CCY_Client { get; set; }
        public virtual DbSet<CCY_Concern> CCY_Concern { get; set; }
        public virtual DbSet<CCY_ImageText> CCY_ImageText { get; set; }
        public virtual DbSet<CCY_Order> CCY_Order { get; set; }
        public virtual DbSet<CCY_User> CCY_User { get; set; }
        public virtual DbSet<CCY_VipPackage> CCY_VipPackage { get; set; }
        public virtual DbSet<CCY_WxConfig> CCY_WxConfig { get; set; }
    }
}
